### ISSUE TITLE
电影选座 App

### ISSUE THREAD

**Issue by xgqfrms** [learning-js-by-reading-source-codes/vanillawebprojects#1]
# 电影选座 App

```html

<div class="screen">
  <span id="screen">屏幕🖥</span>
</div>

```

```css
.screen {
  background-color: #fff;
  height: 70px;
  width: 100%;
  margin: 15px 0;
  transform: rotateX(-45deg);
  box-shadow: 0 3px 10px rgb(255 255 255 / 70%);
  color: #000;
  display: flex;
  align-items: center;
  justify-content: center;
}

```

https://vanillawebprojects.com/projects/movie-seat-booking/
